# Generated by Django 4.2.29 on 2026-04-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0002_alter_newspostmedia_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspostmedia',
            name='is_banner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newspostmedia',
            name='section_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
