# Generated by Django 4.2.30 on 2026-05-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0011_committeemember_username_volunteer_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'President'), ('vice_president', 'Vice President'), ('secretary', 'Secretary')], max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(blank=True, default='', max_length=150)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
